version: 0.2
phases:
  pre_build:
    commands:
    - echo "Set NPM Registry to Artifactory"
    - echo "Run npm install"
    - npm install
  build:
    commands:
    - echo "Build started on $(date)"
    - echo "Build module"
    - npm run test
    - WEB_BUCKET=random-workout-generator-contentbucket-9ph9yu2y312f
    - aws s3 sync ./src s3://$WEB_BUCKET/ --exclude index.html
    - aws s3 cp ./src/index.html s3://$WEB_BUCKET/ --cache-control max-age=0
  post_build:
    commands:
    - echo "Build completed  on $(date)"
artifacts:
  files:
  - '**/*'
  base-directory: src
cache:
  paths:
  - node_modules/**/*
