version: 0.2
phases:
  pre_build:
    commands:
    - echo "Set NPM Registry to Artifactory"
    - echo "Run npm install"
    - npm install
  build:
    commands:
    - echo "Build started on $(date)"
    - echo "Build module"
    - npm run test
  post_build:
    commands:
    - echo "Build completed on $(date)"
artifacts:
  files:
  - src/**/*
  base-directory: src
cache:
  paths:
  - node_modules/**/*
